fix: CI docker build cleanup

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,5 +1,5 @@
-name: CI
-# todo- cleanup CI with only required jobs
+name: CI - Lint and Unit Test
+
 on:
   push:
     branches:
@@ -10,9 +10,7 @@ on:
   workflow_dispatch:
 
 permissions:
-  id-token: write
   contents: read
-  packages: write
 
 jobs:
   checkout-unit-tests:
@@ -28,44 +26,6 @@ jobs:
 
       - name: Unit Tests
         run: bash build/unit-test.sh
-
-  docker-build:
-    name: Docker Build (PR)
-    if: github.event_name == 'pull_request'
-    needs: [ checkout-unit-tests ]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-        with:
-          ref: ${{ github.ref }}
-          clean: true
-
-      - name: Build Docker image
-        run: |
-          docker build -t ghcr.io/cisco-eti/ioc-cfn-svc:latest -f build/Dockerfile .
-
-  call-docker-build-push:
-    name: Docker Build & Push (Main)
-    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
-    needs: [ checkout-unit-tests ]
-    uses: cisco-eti/gh-reusable-workflows/.github/workflows/build-push-docker.yaml@production
-
-    secrets:
-      vault-approle-role-id: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
-      vault-approle-secret-id: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
-      ghcr-username: ${{ secrets.GHCR_USERNAME }}
-      ghcr-token: ${{ secrets.GHCR_TOKEN }}
-      ghcr-org-token: ${{ secrets.GHCR_TOKEN }}
-
-    with:
-      runner-group: ubuntu-latest
-      image-name: "ioc-cfn-svc"
-      dockerfile: build/Dockerfile
-      ecr-enabled: true
-      artifactory-devhub-enabled: false
-      ghcr-enabled: true
-      ghcr-org-registry: ${{ vars.GHCR_REGISTRY }}
 
 #  call-corona-blackduck-scan:
 #    name: Call Corona & Blackduck scan
@@ -136,12 +96,15 @@ jobs:
 
   reusable-workflow-ci-status:
     name: CI Status
-    needs: [ checkout-unit-tests, docker-build, call-docker-build-push]
+    needs: [ checkout-unit-tests ]
     if: always()
     runs-on: ubuntu-latest
     steps:
       - name: Check status
         if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
-        run: exit 1
+        run: |
+          echo "*** WORKFLOW FAILED ***"
+          exit 1
       - name: Success
-        run: echo "CI passed"
+        run: |
+          echo "*** WORKFLOW SUCCESS ***"
